import { http, HttpResponse } from 'msw';

export const handlers = [
  // OpenAI API mocks
  http.post('https://api.openai.com/v1/chat/completions', ({ request }) => {
    const url = new URL(request.url);
    if (url.searchParams.get('error') === 'rate_limit') {
      return HttpResponse.json(
        {
          error: {
            message: 'Rate limit exceeded',
            type: 'rate_limit_error',
          },
        },
        { status: 429 }
      );
    }
    if (url.searchParams.get('error') === 'invalid_key') {
      return HttpResponse.json(
        {
          error: {
            message: 'Invalid API key',
            type: 'invalid_request_error',
          },
        },
        { status: 401 }
      );
    }

    return HttpResponse.json({
      id: 'chatcmpl-test-1234567890',
      object: 'chat.completion',
      created: Date.now(),
      model: 'gpt-3.5-turbo',
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: 'This is a test reply generated by OpenAI.',
          },
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: 10,
        completion_tokens: 15,
        total_tokens: 25,
      },
    });
  }),

  // Groq API mocks
  http.post('https://api.groq.com/openai/v1/chat/completions', () => {
    return HttpResponse.json({
      id: 'chatcmpl-test-1234567890',
      object: 'chat.completion',
      created: Date.now(),
      model: 'meta-llama/llama-4-scout-17b-16e-instruct',
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: 'This is a test reply generated by Groq.',
          },
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: 10,
        completion_tokens: 15,
        total_tokens: 25,
      },
    });
  }),
];
