import { http, HttpResponse } from 'msw';

export const handlers = [
  // Stripe API mocks
  http.post('https://api.stripe.com/v1/checkout/sessions', () => {
    return HttpResponse.json({
      id: 'cs_test_1234567890',
      object: 'checkout.session',
      url: 'https://checkout.stripe.com/test-session',
      payment_status: 'unpaid',
      status: 'open',
    });
  }),

  http.post('https://api.stripe.com/v1/billing_portal/sessions', () => {
    return HttpResponse.json({
      id: 'bps_test_1234567890',
      object: 'billing_portal.session',
      url: 'https://billing.stripe.com/test-session',
    });
  }),

  http.get('https://api.stripe.com/v1/events/:eventId', () => {
    return HttpResponse.json({
      id: 'evt_test_1234567890',
      object: 'event',
      type: 'checkout.session.completed',
      data: {
        object: {
          id: 'cs_test_1234567890',
          object: 'checkout.session',
          customer: 'cus_test_1234567890',
          metadata: {
            userId: 'test-user-1',
            planCode: 'monthly',
          },
        },
      },
    });
  }),

  // OpenAI API mocks
  http.post('https://api.openai.com/v1/chat/completions', () => {
    return HttpResponse.json({
      id: 'chatcmpl-test-1234567890',
      object: 'chat.completion',
      created: Date.now(),
      model: 'gpt-3.5-turbo',
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: 'This is a test reply generated by OpenAI.',
          },
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: 10,
        completion_tokens: 15,
        total_tokens: 25,
      },
    });
  }),

  // Error scenarios
  http.post('https://api.openai.com/v1/chat/completions', ({ request }) => {
    const url = new URL(request.url);
    if (url.searchParams.get('error') === 'rate_limit') {
      return HttpResponse.json(
        {
          error: {
            message: 'Rate limit exceeded',
            type: 'rate_limit_error',
          },
        },
        { status: 429 }
      );
    }
    if (url.searchParams.get('error') === 'invalid_key') {
      return HttpResponse.json(
        {
          error: {
            message: 'Invalid API key',
            type: 'invalid_request_error',
          },
        },
        { status: 401 }
      );
    }
    return HttpResponse.json({
      id: 'chatcmpl-test-1234567890',
      object: 'chat.completion',
      created: Date.now(),
      model: 'gpt-3.5-turbo',
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: 'This is a test reply generated by OpenAI.',
          },
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: 10,
        completion_tokens: 15,
        total_tokens: 25,
      },
    });
  }),
];
